FROM python:3.8-slim-buster

ARG DDT_ENV
ARG DDT_SRC_DIR
ARG POETRY_VERSION

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get install gcc libaio1 unzip libldap2-dev libsasl2-dev ldap-utils libpq-dev postgresql postgresql-contrib musl-dev libssl-dev -y \
    && apt-get clean

RUN mkdir -p "${DDT_SRC_DIR}"
COPY ./api/pyproject.toml "${DDT_SRC_DIR}"


RUN mkdir -p /opt/oracle
WORKDIR /opt/oracle
COPY ./api/instantclient-basic-linux.x64-11.2.0.4.0.zip /opt/oracle
RUN unzip instantclient-basic-linux.x64-11.2.0.4.0.zip
RUN sh -c "echo /opt/oracle/instantclient_11_2 > /etc/ld.so.conf.d/oracle-instantclient.conf"
RUN ldconfig
RUN export LD_LIBRARY_PATH=/opt/oracle/instantclient_11_2:$LD_LIBRARY_PATH
RUN export PATH=/opt/oracle/instantclient_11_2:$PATH

WORKDIR "${DDT_SRC_DIR}"/
RUN \
    mkdir -p "${DDT_SRC_DIR}" && \
    pip --disable-pip-version-check install "poetry==$POETRY_VERSION" && \
    poetry config virtualenvs.create false


RUN poetry install $(test "${DDT_ENV}" = "prod" && echo "--no-dev") --no-interaction --no-ansi

# Install pip requirements
# COPY ./api/requeriments.txt "${DDT_SRC_DIR}"
# RUN python -m pip install -r requirements.txt

# Copy project into volume

COPY ./api/ "${DDT_SRC_DIR}"/

RUN useradd appuser && \
    groupadd appgroup && \
    usermod -G appgroup appuser
RUN chown -R appuser:appgroup "${DDT_SRC_DIR}"
USER appuser