FROM node:lts-alpine

ARG DDT_ROOT

# install simple http server for serving static content
RUN \
    mkdir -p "${DDT_ROOT}" && \
    npm install -g http-server --unsafe-perm

COPY ./frontend/ "${DDT_ROOT}"/
WORKDIR "${DDT_ROOT}"/

RUN npm install