FROM python:3.8-slim-buster

ARG DDT_ENV
ARG DDT_SRC_DIR
ARG POETRY_VERSION

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
&& apt-get install gcc libldap2-dev libpq-dev postgresql postgresql-contrib musl-dev libsasl2-dev libldap2-dev libssl-dev -y \
&& apt-get clean

RUN mkdir -p "${DDT_SRC_DIR}"
COPY ./api/pyproject.toml "${DDT_SRC_DIR}"

WORKDIR "${DDT_SRC_DIR}"/

RUN \
    mkdir -p "${DDT_SRC_DIR}" && \
    pip --disable-pip-version-check install "poetry==$POETRY_VERSION" && \
    poetry config virtualenvs.create false


RUN poetry install $(test "${DDT_ENV}" = "prod" && echo "--no-dev") --no-interaction --no-ansi

# Copy project into volume

COPY ./api/ "${DDT_SRC_DIR}"/

RUN useradd appuser && \
    groupadd appgroup && \
    usermod -G appgroup appuser
RUN chown -R appuser:appgroup "${DDT_SRC_DIR}"
RUN ls "${DDT_SRC_DIR}"/
User appuser